//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuzuBot.Modules.Useful.Satellite {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SATCAT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SATCAT() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuzuBot.Modules.Useful.Satellite.SATCAT", typeof(SATCAT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;AFETR&quot;:&quot;美国佛罗里达州空军东部试验场&quot;,&quot;AFWTR&quot;:&quot;美国加利福尼亚州空军西部试验场&quot;,&quot;CAS&quot;:&quot;金丝雀领空&quot;,&quot;DLS&quot;:&quot;俄罗斯东巴罗夫斯基发射场&quot;,&quot;ERAS&quot;:&quot;东部空域&quot;,&quot;FRGUI&quot;:&quot;欧洲太空港，库鲁，法属圭亚那&quot;,&quot;HGSTR&quot;:&quot;哈马吉拉太空轨道靶场，阿尔及利亚&quot;,&quot;JSC&quot;:&quot;中国酒泉航天中心&quot;,&quot;KODAK&quot;:&quot;美国阿拉斯加州科迪亚克发射场&quot;,&quot;KSCUT&quot;:&quot;内浦宇宙中心（原鹿儿岛宇宙中心——日本东京大学）&quot;,&quot;KWAJ&quot;:&quot;美国陆军夸贾林环礁（USAKA）&quot;,&quot;KYMSC&quot;:&quot;卡普斯京亚尔导弹和太空综合体，俄罗斯&quot;,&quot;NSC&quot;:&quot;大韩民国那老航天中心&quot;,&quot;PLMSC&quot;:&quot;普列谢茨克导弹和太空综合体，俄罗斯&quot;,&quot;RLLB&quot;:&quot;火箭实验室发射基地，马希亚半岛，新西兰&quot;,&quot;SEAL&quot;:&quot;海上发射平台（移动）&quot;,&quot;SEMLS&quot;:&quot;伊朗塞姆南卫星发射场&quot;,&quot;SMTS&quot;:&quot;沙赫鲁德导弹试验场，伊朗&quot;,&quot;SNMLP&quot;:&quot;圣马可发射平台，印度洋（肯尼亚）&quot;,&quot;SRILR&quot;:&quot;印度 Satish Dhawan 航天中心（原 Sriharikota 发射场）&quot;,&quot;SUBL&quot;:&quot;潜艇 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string LAUNCH_SITE_DICT_JSON {
            get {
                return ResourceManager.GetString("LAUNCH_SITE_DICT_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;AB&quot;:&quot;阿拉伯卫星通信组织&quot;,&quot;ABS&quot;:&quot;亚洲广播卫星&quot;,&quot;AC&quot;:&quot;亚洲卫星通讯公司 (ASIASAT)&quot;,&quot;ALG&quot;:&quot;阿尔及利亚&quot;,&quot;ANG&quot;:&quot;安哥拉&quot;,&quot;ARGN&quot;:&quot;阿根廷&quot;,&quot;ASRA&quot;:&quot;奥地利&quot;,&quot;AUS&quot;:&quot;澳大利亚&quot;,&quot;AZER&quot;:&quot;阿塞拜疆&quot;,&quot;BEL&quot;:&quot;比利时&quot;,&quot;BELA&quot;:&quot;白俄罗斯&quot;,&quot;BERM&quot;:&quot;百慕大&quot;,&quot;BGD&quot;:&quot;孟加拉人民共和国&quot;,&quot;BHUT&quot;:&quot;不丹王国&quot;,&quot;BOL&quot;:&quot;玻利维亚&quot;,&quot;BRAZ&quot;:&quot;巴西&quot;,&quot;BUL&quot;:&quot;保加利亚&quot;,&quot;CA&quot;:&quot;加拿大&quot;,&quot;CHBZ&quot;:&quot;中国/巴西&quot;,&quot;CHLE&quot;:&quot;智利&quot;,&quot;CIS&quot;:&quot;独立国家联合体（前苏联）&quot;,&quot;COL&quot;:&quot;哥伦比亚&quot;,&quot;CRI&quot;:&quot;哥斯达黎加共和国&quot;,&quot;CZCH&quot;:&quot;捷克共和国（前捷克斯洛伐克）&quot;,&quot;DEN&quot;:&quot;丹麦&quot;,&quot;ECU&quot;:&quot;厄瓜多尔&quot;,&quot;EGYP&quot;:&quot;埃及&quot;,&quot;ESA&quot;:&quot;欧洲航天局&quot;,&quot;ESRO&quot;:&quot;欧洲空间研究组织&quot;,&quot;EST&quot... 的本地化字符串。
        /// </summary>
        public static string SOURCE_CODE_DICT_JSON {
            get {
                return ResourceManager.GetString("SOURCE_CODE_DICT_JSON", resourceCulture);
            }
        }
    }
}
