name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.token }}
        submodules: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
#    - name: Publish
#      run:  dotnet publish -c Release --no-self-contained -f net60 -o publish
      
#    - name: Stop current program
#      uses: garygrossgarten/github-action-ssh@v0.6.3
#      with:
#        command: |
#          sudo screen -S rin -X stuff $'\003'
#        host: ${{ secrets.host }}
#        port: ${{ secrets.port }}
#        username: ${{ secrets.username }}
#        password: ${{ secrets.password }}
        
#    - name: Copy folder content recursively to remote
#      uses: garygrossgarten/github-action-scp@v0.7.3
#      with:
#        local: publish
#        remote: /home/RinBot_Kotana/publish
#        host: ${{ secrets.host }}
#        port: ${{ secrets.port }}
#        username: ${{ secrets.username }}
#        password: ${{ secrets.password }}
        
#    - name: Run new program
#      uses: garygrossgarten/github-action-ssh@v0.6.3
#      with:
#        command: |
#          screen -S rin -X exec dotnet /home/RinBot_Kotana/publish/ProjektRin.dll
#        host: ${{ secrets.host }}
#        port: ${{ secrets.port }}
#        username: ${{ secrets.username }}
#        password: ${{ secrets.password }}
    
  
