name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.token }}
        submodules: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /
          remote: /home/RinBot_Kotana/publish
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          

    
  
